### ISSUE TITLE
Generated strings/passwords do not always have at-least 1 character of the specified set

### ISSUE THREAD

**Issue by BrycePC** [ljnath/RandomString4Net#1]
Hi, I've been looking at options of using RandomString4Net to satisfy our password requirements of having:
1. >9 characters 
2. At least 1 upper-case & 1 lowercase character
3. At least 1 symbol
4. At least 1 number

I was hoping that RandomString.GetString(Types.ALPHANUMERIC_MIXEDCASE_WITH_SYMBOLS, 10) would provide us with what we want; ie at least 1 character of each. This does not appear to be the case though; example generated values include:

 FBKl%.=>VT (no number)
=#h5\1j-r: (no uppercase character)

Is this a feature that can be supported in the future?

Thanks,

Bryce

**Comment by ljnath** [comment]
@BrycePC , thank you for your feedback. Currently the generator is not strict with the input, due to which you are not getting the expected result. 
I will make the changes and will release a new version in few days.

Cheers

**Comment by BrycePC** [comment]
Thanks for your help @ljnath !

**Comment by ljnath** [comment]
@BrycePC , I have added the feature and a new version 1.4.0 has been released. 
To achieve your requirement a new boolean flag `forceOccuranceOfEachType` has been added, when `forceOccuranceOfEachType:true`, characters for each sub-type will be used during the random string generation.

In your case, you can try 
`RandomString.GetString(Types.ALPHANUMERIC_MIXEDCASE_WITH_SYMBOLS, count:10, forceOccuranceOfEachType:true)`

**Comment by BrycePC** [comment]
Thanks again @ljnath , I will grab this latest version for our next changes.
Cheers,
Bryce

**Comment by ljnath** [comment]
@BrycePC , thank you. I will close this issue for now; feel free tp create one if encounter any.
