### ISSUE TITLE
forceUnique can generete less strings than requested

### ISSUE THREAD

**Issue by Mart-Bogdan** [ljnath/RandomString4Net#3]
In this loop if this option is set

https://github.com/ljnath/RandomString4Net/blob/f01e28844ff909906fcf5cd08ab4aaaf9586a33e/RandomString4Net/RandomString.cs#L194-L206

it just skips current string (index)
https://github.com/ljnath/RandomString4Net/blob/f01e28844ff909906fcf5cd08ab4aaaf9586a33e/RandomString4Net/RandomString.cs#L202-L203

But it should **retry** to generate non repetitive string. 

**P.S.**  same for second method

https://github.com/ljnath/RandomString4Net/blob/f01e28844ff909906fcf5cd08ab4aaaf9586a33e/RandomString4Net/RandomString.cs#L239-L240

**Comment by ljnath** [comment]
@Mart-Bogdan , thank you for raising this issue.
Can you please explain `it just skips current string (index)` and share a test scenario.

I am tried `RandomString.GetStrings(Types.NUMBERS, 2, 10, false, true, forceOccuranceOfEachType: false)` , I did get 2 random strings

**Comment by ljnath** [comment]
This is expected as the number of random strings will decreased when all characters are mandatorily used.
